name: discord-notify

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Send notification to discord channel
        run: echo Send notification to discord channel

      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Warn
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Test warning.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Error
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Test error.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

#      - name: Discord Webhook Action
#        uses: tsickert/discord-webhook@v5.3.0
#        with:
#          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
#          content: "New push to Gym-App Repo"

#      - name: Discord notification
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        uses: Ilshidur/action-discord@master
#        with:
#          args: 'New push to Gym-App Repo'
