name: Push
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Make gradlew executable
        run: git update-index --chmod=+x gradlew
