#name: Push
#on:
#  push:
#    branches: [ master ]
#  workflow_dispatch:
#
#jobs:
#  clean-cache:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Open Script File
#        run: echo Open Script File
#
#      - name: open cleanup file
#        run: sh ./cleanup.sh
#
#  lint:
#    needs: [clean-cache]
#    runs-on: ubuntu-latest
#    steps:
#      - name: CheckOut the code
#        uses: actions/checkout@v2
#
#      - name: Run Lint
#        run: echo Run Lint
#
##      - name: Set up JDK 17
##        uses: actions/setup-java@v1
##        with:
##          java-version: 17
##
##      - name: Run Lint
##        run: ./gradlew lintDebug
##
##      - name: Upload html test report
##        uses: actions/upload-artifact@v2
##        with:
##          name: lint.html
##          path: app/build/reports/lint-results-debug.html
#
#  unit-test:
#    needs: [ lint ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Run test
#        run: echo Run UnitTest
#
##      - name: Set up JDK 17
##        uses: actions/setup-java@v1
##        with:
##          java-version: 17
##
##      - name: Run tests
##        run: ./gradlew test
##
##      - name: Upload test report
##        uses: actions/upload-artifact@v2
##        with:
##          name: unit_test_report
##          path: app/build/reports/tests/testDebugUnitTest/
#
#  instrumentation-test:
#    needs: [unit-test]
#    runs-on: macos-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Run test
#        run: echo Run Test
#
##      - name: Set up JDK 17
##        uses: actions/setup-java@v1
##        with:
##          java-version: 17
##
##      - name: Run espresso tests
##        uses: reactivecircus/android-emulator-runner@v2
##        with:
##          api-level: 29
##          script: ./gradlew connectedCheck
##
##      - name: Upload test report
##        uses: actions/upload-artifact@v2
##        with:
##          name: instrumentation_test_report
##          path: app/build/reports/tests/testDebugUnitTest/
#
#  static-code-analysis:
#    needs: [instrumentation-test]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Run test
#        run: echo Run static code analysis
#
##      - name: Set up JDK 17
##        uses: actions/setup-java@v1
##        with:
##          java-version: 17
##
##      - name: SonarCloud Scan
##        run: ./gradlew sonarqube -Dsonar.login=${{secrets.SONAR_TOKEN}}
##        env:
##          GITHUB_TOKEn: ${{ secrets.GITHUB_TOKEN}}
#
#
#  package:
#    needs: [static-code-analysis]
#    name: Generate APK
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Generate APK
#        run: echo GENERATE APK
#
##      - name: Set up JDK 17
##        uses: actions/setup-java@v1
##        with:
##          java-version: 17
##
##      - name: Build debug APK
##        run: ./gradlew assembleDebug --stacktrace
##
##      - name: Upload APK
##        uses: actions/upload-artifact@v2
##        with:
##          name: gym-app.apk
##          path: app/build/outputs/apk/debug/app-debug.apk
#
